name: iOS unsigned IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Doctor
        run: |
          flutter --version
          flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Install CocoaPods
        run: sudo gem install cocoapods -NV

      - name: Pod install (with repo update)
        run: |
          cd ios
          pod repo update
          pod install --repo-update

      # 可选：先用 Xcode 原生命令做一次“仅编译”，能把第一条编译错误暴露出来（排错更清晰）
      - name: Xcode build (compile only, no codesign)
        run: |
          set -euxo pipefail
          cd ios
          xcodebuild -list -workspace Runner.xcworkspace
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            COMPILER_INDEX_STORE_ENABLE=NO | tee ../xcodebuild.compile.log
          cd ..

      - name: Upload compile log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-compile-log
          path: xcodebuild.compile.log

      # 用 Flutter 产出 Runner.app（无签名）
      - name: Build iOS app (no codesign)
        run: flutter build ios --release --no-codesign -v

      # 手工打包 unsigned IPA：Payload/Runner.app -> Runner.ipa
      - name: Package unsigned IPA
        run: |
          set -euxo pipefail
          APP_PATH="build/ios/iphoneos/Runner.app"
          test -d "$APP_PATH"
          rm -rf build/ios/ipa
          mkdir -p build/ios/ipa/Payload
          cp -R "$APP_PATH" build/ios/ipa/Payload/Runner.app
          (cd build/ios/ipa && /usr/bin/zip -r Runner.ipa Payload)
          ls -lah build/ios/ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: tutu-unsigned-ipa
          path: build/ios/ipa/*.ipa
