name: iOS unsigned IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Doctor
        run: |
          flutter --version
          flutter doctor -v

      # 关键：先生成 ios/Flutter/Generated.xcconfig
      - name: Flutter pub get
        run: flutter pub get

      # 可选但推荐：预拉 iOS 构建产物，避免首次构建下载卡住
      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Install CocoaPods
        run: sudo gem install cocoapods -NV

      - name: Pod install (with repo update)
        run: |
          cd ios
          pod repo update
          pod install --repo-update

      - name: Build IPA (no codesign)
        run: flutter build ipa --release --no-codesign -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tutu-unsigned-ipa
          path: build/ios/ipa/*.ipa
