name: iOS unsigned IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Doctor
        run: |
          flutter --version
          flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Install CocoaPods
        run: sudo gem install cocoapods -NV

      - name: Pod install (with repo update)
        run: |
          cd ios
          pod repo update
          pod install --repo-update

      # 先用 Xcode 原生命令做一次“仅编译”，这样能把真正的第一条 error 打出来
      - name: Xcode build (compile only, no codesign)
        run: |
          set -euxo pipefail
          cd ios
          xcodebuild -list -workspace Runner.xcworkspace
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            COMPILER_INDEX_STORE_ENABLE=NO | tee ../xcodebuild.compile.log
          cd ..
      - name: Upload compile log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcodebuild-compile-log
          path: xcodebuild.compile.log

      # 再用 Flutter 的官方打包命令产出无签名 IPA
      - name: Build IPA (no codesign)
        run: flutter build ipa --release --no-codesign -v

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: tutu-unsigned-ipa
          path: build/ios/ipa/*.ipa
