name: iOS unsigned IPA

on:
  push:
    branches: [ main ]
    paths:
      - "ios/**"
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ios/Pods
            ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Flutter Pub Get
        run: flutter pub get

      - name: CocoaPods Install
        run: |
          set -euxo pipefail
          cd ios
          pod install --repo-update

      - name: Analyze
        run: flutter analyze

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 手动把 .app 打成未签名 IPA
      - name: Package unsigned IPA
        run: |
          set -euxo pipefail
          APP_PATH="build/ios/iphoneos/Runner.app"
          test -d "$APP_PATH"
          rm -rf build/ios/ipa
          mkdir -p build/ios/ipa/Payload
          cp -R "$APP_PATH" build/ios/ipa/Payload/Runner.app
          (cd build/ios/ipa && /usr/bin/zip -r Runner.ipa Payload)
          ls -lah build/ios/ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: tutu-unsigned-ipa
          path: build/ios/ipa/*.ipa
