name: iOS unsigned IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14   # Apple Silicon runner
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Doctor
        run: |
          flutter --version
          flutter doctor -v

      - name: Install CocoaPods
        run: sudo gem install cocoapods -NV

      - name: Pod install (with repo update)
        run: |
          cd ios
          pod repo update
          pod install --repo-update

      # 关键：用官方的 ipa 构建而不是手工 zip
      - name: Build IPA (no codesign)
        run: flutter build ipa --release --no-codesign -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tutu-unsigned-ipa
          path: build/ios/ipa/*.ipa
