name: iOS unsigned IPA

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      - name: Ensure CocoaPods
        run: sudo gem install cocoapods -NV || true

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Package .ipa
        shell: bash
        run: |
          rm -rf Payload && mkdir Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          /usr/bin/zip -qry tutu-unsigned.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tutu-unsigned-ipa
          path: tutu-unsigned.ipa
